### ISSUE TITLE
OAuth callback URL cannot be localhost which conflicts with the default startup host

### ISSUE THREAD

**Issue by cmacher** [openforce/spark-mllib-scala-play#21]
Activator and Play Framework start the application by default with localhost:9000. The OAuth configuration for a Twitter App requires to set a callback URL. This cannot be localhost but has to be 127.0.0.1 instead. Therefore we have a problem when we want to access cookies which are stored with a different host.

**Comment by nano4711** [comment]
Found this out by the hard way too. Thanks for pointing this out.

**Comment by cmacher** [comment]
Won't be relevant as soon as we have a single-user-mode flag #22 .
